/* =========================================================
   LUMINA photo data - generated by scripts/import-photos.ps1
   ---------------------------------------------------------
   FIELDS: src / thumb (grid) / title / category / year / camera
   OPTIONAL: place (location) - add it and it shows in the overlay
   CATEGORY KEYS must match the keys of window.PHOTO_CATEGORIES.
   ========================================================= */

window.PHOTO_CATEGORIES = {
  landscape: '风光',
  animal: '动物',
  architecture: '建筑',
  street: '街拍',
  plant: '花草'
};

window.PHOTOS = [
  {
    src: 'images/work-01.jpg',
    thumb: 'images/thumbs/work-01.jpg',
    title: '霞映湖城',
    category: 'landscape',
    year: '2025',
    camera: 'OPPO Reno13 · f/2.2 · 1/1957s · ISO 50'
  },
  {
    src: 'images/work-02.jpg',
    thumb: 'images/thumbs/work-02.jpg',
    title: '碧水双鹅',
    category: 'animal',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-03.jpg',
    thumb: 'images/thumbs/work-03.jpg',
    title: '枝影逆光',
    category: 'landscape',
    year: '2025',
    camera: 'OPPO Reno13 · f/1.8 · 1/10000s · ISO 80'
  },
  {
    src: 'images/work-04.jpg',
    thumb: 'images/thumbs/work-04.jpg',
    title: '园林水榭',
    category: 'architecture',
    year: '2025',
    camera: 'OPPO Reno13 · f/2.2 · 1/50s · ISO 160'
  },
  {
    src: 'images/work-05.jpg',
    thumb: 'images/thumbs/work-05.jpg',
    title: '窗台小憩',
    category: 'animal',
    year: '2025',
    camera: 'f/1.8 · 1/20s · ISO 2500'
  },
  {
    src: 'images/work-06.jpg',
    thumb: 'images/thumbs/work-06.jpg',
    title: '夕照柳垂',
    category: 'landscape',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/67s · ISO 250'
  },
  {
    src: 'images/work-07.jpg',
    thumb: 'images/thumbs/work-07.jpg',
    title: '夜巷灯火',
    category: 'street',
    year: '2025',
    camera: 'OPPO Reno13 · f/1.8 · 1/20s · ISO 1600'
  },
  {
    src: 'images/work-08.jpg',
    thumb: 'images/thumbs/work-08.jpg',
    title: '暗香·其一',
    category: 'plant',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/20s · ISO 4000'
  },
  {
    src: 'images/work-09.jpg',
    thumb: 'images/thumbs/work-09.jpg',
    title: '夜湖倒影',
    category: 'architecture',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/26s · ISO 1250'
  },
  {
    src: 'images/work-10.jpg',
    thumb: 'images/thumbs/work-10.jpg',
    title: '粉霞满湖',
    category: 'landscape',
    year: '2026',
    camera: 'OPPO Reno13 · f/2.2 · 1/50s · ISO 64'
  },
  {
    src: 'images/work-11.jpg',
    thumb: 'images/thumbs/work-11.jpg',
    title: '绿地白猫',
    category: 'animal',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/409s · ISO 80'
  },
  {
    src: 'images/work-12.jpg',
    thumb: 'images/thumbs/work-12.jpg',
    title: '湖光柳色',
    category: 'landscape',
    year: '2026',
    camera: 'OPPO Reno13 · f/2.2 · 1/4892s · ISO 64'
  },
  {
    src: 'images/work-13.jpg',
    thumb: 'images/thumbs/work-13.jpg',
    title: '黄昏街头',
    category: 'street',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-14.jpg',
    thumb: 'images/thumbs/work-14.jpg',
    title: '曲廊花窗',
    category: 'architecture',
    year: '2025',
    camera: 'OPPO Reno13 · f/1.8 · 1/50s · ISO 500'
  },
  {
    src: 'images/work-15.jpg',
    thumb: 'images/thumbs/work-15.jpg',
    title: '落日孤树',
    category: 'landscape',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/50s · ISO 800'
  },
  {
    src: 'images/work-16.jpg',
    thumb: 'images/thumbs/work-16.jpg',
    title: '与天鹅的问候',
    category: 'animal',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-17.jpg',
    thumb: 'images/thumbs/work-17.jpg',
    title: '暮色水影',
    category: 'landscape',
    year: '2025',
    camera: 'OPPO Reno13 · f/1.8 · 1/33s · ISO 2000'
  },
  {
    src: 'images/work-18.jpg',
    thumb: 'images/thumbs/work-18.jpg',
    title: '秋草落枝',
    category: 'plant',
    year: '2025',
    camera: 'OPPO Reno13 · f/1.8 · 1/251s · ISO 80'
  },
  {
    src: 'images/work-19.jpg',
    thumb: 'images/thumbs/work-19.jpg',
    title: '云过楼宇',
    category: 'architecture',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/741s · ISO 80'
  },
  {
    src: 'images/work-20.jpg',
    thumb: 'images/thumbs/work-20.jpg',
    title: '夕照天际',
    category: 'landscape',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/50s · ISO 800'
  },
  {
    src: 'images/work-21.jpg',
    thumb: 'images/thumbs/work-21.jpg',
    title: '雨夜树影',
    category: 'street',
    year: '2025',
    camera: 'OPPO Reno13 · f/1.8 · 1/20s · ISO 1000'
  },
  {
    src: 'images/work-22.jpg',
    thumb: 'images/thumbs/work-22.jpg',
    title: '晚霞映路',
    category: 'landscape',
    year: '2026',
    camera: 'OPPO Reno13 · f/2.2 · 1/50s · ISO 64'
  },
  {
    src: 'images/work-23.jpg',
    thumb: 'images/thumbs/work-23.jpg',
    title: '草地狸花',
    category: 'animal',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-24.jpg',
    thumb: 'images/thumbs/work-24.jpg',
    title: '月出林梢',
    category: 'landscape',
    year: '2025',
    camera: 'OPPO Reno13 · f/1.8 · 1/17s · ISO 12800'
  },
  {
    src: 'images/work-25.jpg',
    thumb: 'images/thumbs/work-25.jpg',
    title: '楼前新绿',
    category: 'architecture',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-26.jpg',
    thumb: 'images/thumbs/work-26.jpg',
    title: '胜利之夜',
    category: 'street',
    year: '2026',
    camera: 'OPPO Reno13 · f/2.2 · 1/30s · ISO 200'
  },
  {
    src: 'images/work-27.jpg',
    thumb: 'images/thumbs/work-27.jpg',
    title: '湖上暮色',
    category: 'landscape',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/100s · ISO 100'
  },
  {
    src: 'images/work-28.jpg',
    thumb: 'images/thumbs/work-28.jpg',
    title: '柳荫湖道',
    category: 'landscape',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-29.jpg',
    thumb: 'images/thumbs/work-29.jpg',
    title: '暗香·其二',
    category: 'plant',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/20s · ISO 4000'
  },
  {
    src: 'images/work-30.jpg',
    thumb: 'images/thumbs/work-30.jpg',
    title: '看台之上',
    category: 'architecture',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-31.jpg',
    thumb: 'images/thumbs/work-31.jpg',
    title: '暮湖柳影',
    category: 'landscape',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/40s · ISO 1000'
  },
  {
    src: 'images/work-32.jpg',
    thumb: 'images/thumbs/work-32.jpg',
    title: '暮水归鸭',
    category: 'animal',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/26s · ISO 1250'
  },
  {
    src: 'images/work-33.jpg',
    thumb: 'images/thumbs/work-33.jpg',
    title: '湖城夕照',
    category: 'landscape',
    year: '2026',
    camera: 'OPPO Reno13 · f/1.8 · 1/100s · ISO 100'
  },
  {
    src: 'images/work-34.jpg',
    thumb: 'images/thumbs/work-34.jpg',
    title: '云影入湖',
    category: 'landscape',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-35.jpg',
    thumb: 'images/thumbs/work-35.jpg',
    title: '晨光公路',
    category: 'landscape',
    year: '2025',
    camera: ''
  },
  {
    src: 'images/work-36.jpg',
    thumb: 'images/thumbs/work-36.jpg',
    title: '球场向晚',
    category: 'architecture',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-37.jpg',
    thumb: 'images/thumbs/work-37.jpg',
    title: '草地闲鹅',
    category: 'animal',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-38.jpg',
    thumb: 'images/thumbs/work-38.jpg',
    title: '叶隙碎光',
    category: 'plant',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-39.jpg',
    thumb: 'images/thumbs/work-39.jpg',
    title: '操场与树',
    category: 'architecture',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-40.jpg',
    thumb: 'images/thumbs/work-40.jpg',
    title: '湖畔柳径',
    category: 'landscape',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-41.jpg',
    thumb: 'images/thumbs/work-41.jpg',
    title: '仰见流云',
    category: 'landscape',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-42.jpg',
    thumb: 'images/thumbs/work-42.jpg',
    title: '云涌湖天',
    category: 'landscape',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-43.jpg',
    thumb: 'images/thumbs/work-43.jpg',
    title: '夕照湖畔',
    category: 'landscape',
    year: '',
    camera: ''
  },
  {
    src: 'images/work-44.jpg',
    thumb: 'images/thumbs/work-44.jpg',
    title: '金波戏鸭',
    category: 'animal',
    year: '',
    camera: ''
  }
];